title: RyskillTV
author: Ryskill
email: ryskilltv@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 RyskillTV.com

# social links
twitter_username: RyskillTV
github_username:  markjhunsinger

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
